### PR TITLE
Add i and ? buttons in the ComparativeSystems submission form

### PR DESCRIPTION
**Pull request by chmao1**
https://github.com/BV-BRC/issues/issues/1340

### CODE REVIEW

**Comment by olsonanl** [comment]
Will the docs change work properly with the current production site?

**Comment by chmao1** [comment]
> Will the docs change work properly with the current production site?

Yes. Please see: https://github.com/BV-BRC/BV-BRC-Docs/pull/125

**Comment by olsonanl** [comment]
OK, good. I ask because we're on the Feb release cycle for the website so this change won't show up in production until then.

**Comment by chmao1** [comment]
> OK, good. I ask because we're on the Feb release cycle for the website so this change won't show up in production until then.

Actually, the doc change was very minor and is not critical for the submission form changes in this pull request.

**Review by olsonanl — APPROVED** [review]

**Pull request merged**
