### PR TITLE
Arachaeopteryx.js updates

### PR DESCRIPTION
**Pull request by chris-c-thomas**
This PR contains a few things for Arachaeopteryx.

1. First, tracking for the submodule has been set to its master branch as it had been stuck on a detached head. This kept some aspects from updating when I thought it had been. It’s been fast forwarded and new updates/commits added to the submodule. I will point alpha, beta, and production to the correct tracking branch so that git doesn’t report differences when updates are pulled down onto each instance.

2. The newest data XML file, iteration 21, has been copied over to be served from the data api. 

3. VariantLineagePhlyogenyTreeViewer.js updated to reference newest data file.

4. VariantLineagePhlyogenyTreeViewer.js also includes changes that need to be manually applied from voc_example.html / outlined in the email requesting an update.

5. Bundle2.js has been updated to included to newest version of arachaeopteryx.js and its dependancies. This is built using the `make_bundle2.sh` script located within /public/js/bundle and needs to be ran after the submodule has been updated.

### CODE REVIEW

**Comment by chris-c-thomas** [comment]
This should likely get reviewed and tested soon so that the rest of arachaeopteryx and phyloxml viewers are up to date with the latest versions.

Locally, I found the SARS variant tree and the job out trees performing as expected.

**Comment by olsonanl** [comment]
Yes, I need to make time to carefully look at it and test since it seems pretty extensive

**Comment by chris-c-thomas** [comment]
Np. Just bumping for visibility. Need to filter through the which dependabots are worth an upgrade and non breaking.

**Review by olsonanl — APPROVED** [review]
This is fine; on the surface appeared to work on a cherrypicked branch. However we will need to make sure to rebundle when archy changes underneath.

**Pull request merged**
