### PR TITLE
archaeopteryx version 2.0.3a2

### PR DESCRIPTION
**Pull request by cmzmasek**
archaeopteryx version 2.0.3a2
latest SARS-CoV-2 reference tree

### CODE REVIEW

**Comment by chris-c-thomas** [comment]
This updates archy but for it to actually take effect I believe it still requires some work.

`bundle2.js` for instance needs to be recompiled since that's currently on v2.0.2a1 and the XML files need to be referenced

**Comment by olsonanl** [comment]
Thanks. You should be able to rebuild it using the script in that directory and check in the updated bundle.
________________________________

**Review by olsonanl — APPROVED** [review]

**Comment by olsonanl** [comment]
Christian, this update is in for alpha. Can you verify it is working as intended?

**Comment by cmzmasek** [comment]
I can confirm that Archaeopteryx.js 2.0.3a2 works as intended on alpha.

**Pull request merged**
